#!/bin/bash

# Grab the first argument which is the title of the article.
SUBJECT=${1}
echo "Subject: $SUBJECT"
echo ""

# Translate input into format expected by Wikipedia for whitespace delimited topics like "cold brew" or "George Washington".
NEW_SUBJECT=$(echo "$SUBJECT" | tr ' ' '_')
echo "New Subject: $NEW_SUBJECT"
echo ""

# Get the webpage for the Wikipedia article and store output in a variable.
ARTICLE=$(curl -s --location https://en.wikipedia.org/wiki/$SUBJECT)

# Process part of the article to get the first sentence.
FIRST_SENTENCE=$(echo "$ARTICLE" | grep "$SUBJECT" | head -n 5 | grep "<p>" | head -n 1 | cut -d'.' -f1)
PLAIN_SENTENCE=$(echo "$FIRST_SENTENCE" | sed -E $'s/>/#\\\n/g' | sed -E $'s/</\\\n#/g' | grep -v "#" | tr -d '\n')

# Grab list of first level section headings.
SECTION_HEADINGS=$(echo "$ARTICLE" |  grep -n "toclevel-1" | tr "<" "\n" | grep "href" | tr '"' '\n' | grep "#" | tr -d "#")

# Output to the user.
echo "${PLAIN_SENTENCE}."
echo ""
echo -e "Contents:\n"
echo "$SECTION_HEADINGS"
echo ""
