#!/bin/bash

# Grab the first argument which is the title of the article.
SUBJECT=${1}

echo "###################################"
echo -e "Subject: $SUBJECT \n"

# Get the webpage for the Wikipedia article.
#ARTICLE=$(curl --location https://en.wikipedia.org/wiki/$SUBJECT)

# Limit output for easier  debugging.
echo "###################################"
#echo "$ARTICLE" | head -n 7

# Look up how to suppress metrics and error messages from curl so that they are not output by the script.
FIRST_SENTENCE=$(curl --location https://en.wikipedia.org/wiki/$SUBJECT | grep "walrus" | head -n 5 | grep "<p>" | head -n 1 | cut -d'.' -f1)
echo "$FIRST_SENTENCE"
echo ""


# Grab list of first level section headings and output them.
echo "###################################"
echo -e "Contents:\n"
SECTION_HEADINGS=$(grep -n "toclevel-1" walrus.html | tr "<" "\n" | grep "href" | tr '"' '\n' | grep "#" | tr -d "#")
echo "$SECTION_HEADINGS"
